language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

services:
  - docker

install:
  - go get github.com/mattn/go-tty
  - go get github.com/mattn/go-isatty
  - go get github.com/mattn/go-colorable
  - go get github.com/mattn/go-runewidth
  - go get github.com/c-bata/go-prompt
  - go get github.com/pkg/term
  - go get golang.org/x/sync
  - go get golang.org/x/sys
  - make all
