language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

os:
  - linux
  - osx

dist: bionic
sudo: true

services:
  - docker

install:
  - go get github.com/c-bata/go-prompt
  - make all
